### 01 - Teste de gravidez
Escreva uma célula com controle de fluxos que tem como premissa a existência das seguintes variáveis:

- ```sexo``` como ```str``` indicando os valores '**M**' para masculino e '**F**' para feminino  
- ```beta_hcg``` que indica a quantidade do beta-HCG no sangue em mUI/mL.

A sua tarefa é escrever um código que imprima como resultado "indivíduo do sexo masculino" quando sexo = 'M', caso sexo = 'F', se o valor de beta-HCG for maior que 5, retorne "Positivo" indicando que a paciente está grávida, e retorne "Negativo" caso contrário.

Não mexa nos valores da variável ```sexo``` nem em ```beta_hcg```, e escreva um código que funcione para quaisquer valores possíveis de ambos: ```sexo``` = '**M**' ou '**F**' e ```beta_hcg``` assumindo valores inteiros positivos.

In [1]:
sexo = 'M'
beta_hcg = 0

# seu código vem abaixo desta linha
sexo = 'M'
beta_hcg = 0

sexo = str(input('Qual o seu sexo? '))
if sexo == 'M':
    print("Indivíduo do sexo masculino.")
elif sexo == 'F':
    print("Indivíduo do sexo feminino.")

if sexo == 'F':
    beta_hcg = int(input('Digite o nível de beta-HCG no seu sangue:'))
sexo != 'M'
beta_hcg >= 5

if sexo != 'M' and beta_hcg >= 5:
    print('Positivo para gravidez.')
elif sexo != 'M' and beta_hcg <= 5:
    print('Negativo para gravidez.')


Qual o seu sexo?  M


Indivíduo do sexo masculino.


### 02 - Renomeando variáveis

Vamos ver adiante que uma forma de renomear variáveis de um conjunto de dados é através de dicionários - o dicionário deve conter como chave o nome original, associando a cada chave um único valor (tipo *str*) que contenha o nome novo.

A sua tarefa é escrever um dicionário que possa ser utilizado para traduzir as variáveis ```name``` (nome), ```age``` (idade) e ```income``` (renda). Ou seja, esse dicionário deve relacionar as chaves *name, age* e *income* às suas respectivas traduções.

In [2]:
dic_renomeacao = {'name':'1'}
dic_renomeacao['name'] = 'nome'
dic_renomeacao['age'] = 'idade'
dic_renomeacao['income'] = 'renda'
print(dic_renomeacao)

{'name': 'nome', 'age': 'idade', 'income': 'renda'}


### 03 - É divisível?
A sua tarefa é escrever um código que indique se um número ```N``` é divisível por um número P. Escreva um programa que faça essa verificação para quaisquer combinações de ```N``` e ```M``` e devolva uma mensagem indicativa no output.

In [3]:
N = 42
M = 7

#Seu código

N = 42
M = 7

if(N % M) == 0:
    print('42 é divisível por 7.')
else:
    print('42 não é divisível por 7.')
if(M % N) == 0:
    print('7 é divisível por 42.')
else:
    print('7 não é divisível por 42.')

#Obs. O enunciado faz referência a "N" e "P" e depois menciona
#"quaisquer combinações de 'N' e 'M'". Como no exercício só consatam 
#as variáveis "N" e "M", presumi que houve um erro de digitação.

42 é divisível por 7.
7 não é divisível por 42.


### 04 - Números primos
> Um número **N** é primo se e somente se é divisível por 1, -1, por **N** e por -**N**.  

Escreva um script que verifica se ```N``` é um número primo, verificando se ```N``` é divisível por todos os números de ```1``` a ```N-1```. Você vai precisar usar alguma ferramenta de *loop* que você aprendeu para isto. No final, devolva uma mensagem no output indicando se o número é primo ou não.

In [4]:
N = 47

# seu código abaixo

N = 47
primo = True
i = 2

while i < N and primo:
    if N % i == 0:
        primo = False
    i += 1

if primo:
    print (N, 'é um número primo.')
else:
    print (N, 'não é um número primo.')


47 é um número primo.


### 05 - Desafio
O algorítmo do exercício anterior não é o mais eficiente. O que você pode fazer para deixá-lo mais eficiente? Ou seja, executar menos comparações, portanto consumir menos tempo.
1. Será que precisamos correr o loop até o final sempre?
2. Será que precisamos mesmo verificar **todos** os números?
3. Será que precisamos ir até N-1?

Essas perguntas levam ao tipo de pensamento voltado a deixar um algoritmo mais eficiente. Veja se você consegue melhorar o seu.

In [55]:
N = 98

# seu código aqui

#para resolver o exercício anterior fiz uma pesquisa na internet e encontrei diversos altoritmos diferentes.
#acho que o que escolhi já é o mais simples, correto?


### 06 - Peso ideal 1
O IMC (índice de massa corpórea) é um indicador de saúde mais bem aceito que o peso. Ele é calculado como:

$$ IMC = \dfrac{peso}{altura^2}$$

Segundo a OMS, valores *normais* são entre 18.5 e 24.9.

Sua tarefa é encontrar o ponto médio dessa faixa.

In [7]:


# seu código aqui

imc_normalminimo = float(input('Digite o valor mínimo para IMC:'))
imc_normalmaximo = float(input('Digite o valor máximo para IMC:'))
imc_ideal = (imc_normalminimo + imc_normalmaximo) / 2
print('O ponto médio é', imc_ideal)


Digite o valor mínimo para IMC: 18.5
Digite o valor máximo para IMC: 24.9


O ponto médio é 21.7


### 07 - Peso ideal 2
Recebendo um valor de altura, encontre o peso '*ideal*' dessa pessoa, que fornece o IMC encontrado acima

In [11]:
altura = 1.70

# Seu código

imc_ideal = 21.7
altura = 1.70

peso_ideal = imc_ideal * altura**2
print('O peso ideal é', peso_ideal, 'quilos.')



O peso ideal é 62.712999999999994 quilos.


### 08 - Peso ideal 3
Dada uma lista contendo as alturas de pacientes, crie uma nova lista que contenha o peso '*ideal*' (que fornece o IMC calculado em **Peso ideal 1**) desses pacientes.

In [14]:

# seu código

imc_ideal = 21.7
lista_peso_ideal = []
lista_alturas = [1.95, 2.05, 1.70, 1.65]

peso_ideal_0 = imc_ideal * (lista_alturas[0])**2
print('O peso ideal para altura:', (lista_alturas[0]), 'é', peso_ideal_0, 'quilos.''\n')

peso_ideal_1 = imc_ideal * (lista_alturas[1])**2
print('O peso ideal para altura:', (lista_alturas[1]), 'é', peso_ideal_1, 'quilos.''\n')

peso_ideal_2 = imc_ideal * (lista_alturas[2])**2
print('O peso ideal para altura:', (lista_alturas[2]), 'é', peso_ideal_2, 'quilos.''\n')
    
peso_ideal_3 = imc_ideal * (lista_alturas[3])**2
print('O peso ideal para altura:', (lista_alturas[3]), 'é', peso_ideal_3, 'quilos.','\n')

lista_peso_ideal =[peso_ideal_0, peso_ideal_1, peso_ideal_2, peso_ideal_3]
print(lista_peso_ideal)

O peso ideal para altura: 1.95 é 82.51424999999999 quilos.

O peso ideal para altura: 2.05 é 91.19425 quilos.

O peso ideal para altura: 1.7 é 62.712999999999994 quilos.

O peso ideal para altura: 1.65 é 59.07824999999999 quilos. 

[82.51424999999999, 91.19425, 62.712999999999994, 59.07824999999999]


### 09 - Peso ideal 4
Dada uma lista de tuplas - cada elemento da lista é uma tupla contendo altura e peso de um paciente - crie uma nova lista com o IMC desses pacientes.

In [142]:

# seu código

altura_peso = [(1.80, 90), (1.65, 75), (1.91, 70)]

lista_imc = []
for i in range(len(altura_peso)):
    imc = altura_peso[i][1] / altura_peso[i][0]**2
    lista_imc.append(imc)
print(lista_imc)    

[27.777777777777775, 27.548209366391188, 19.188070502453332]


### 10 - Peso ideal 5
Dada uma lista de **listas** - cada elemento da lista é uma **lista** contendo altura e peso de um paciente, adicione mais um elemento à lista de cada paciente contendo o IMC do paciente. Verifique também se é 'baixo', 'normal' ou 'alto' segundo os padrões da OMS em que normal é entre 18.5 e 24.9.

Reflexão: por que no problema anterior temos que criar uma nova lista, e não podemos adicionar os dados de cada indivíduo à tupla?

In [19]:
altura_peso = [[1.80, 90], [1.65, 75], [1.91, 70]]

# seu código

altura_peso

[[1.8, 90], [1.65, 75], [1.91, 70]]

In [194]:
altura_peso = [[1.80, 90], [1.65, 75], [1.91, 70]]

for i in range(len(altura_peso)):
    imc = altura_peso[i][1] / altura_peso[i][0]**2
    altura_peso[i].append(imc)

print(altura_peso)

print('\n')

for i in range(len(altura_peso)):
    print(altura_peso[i][2])
    if (altura_peso[i][2]) >= 24.9:
        print('alto')
    elif (altura_peso[i][2]) <= 18.5:
        print('baixo')
    else:
        print('normal')




[[1.8, 90, 27.777777777777775], [1.65, 75, 27.548209366391188], [1.91, 70, 19.188070502453332]]


27.777777777777775
alto
27.548209366391188
alto
19.188070502453332
normal
